version: "3"
services:
  postgres-database:
    image: postgres:13.1-alpine
    container_name: api-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 9090:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=student-api-database
    restart: unless-stopped
  # APP*****************************************
  student-api:
    image: student-api-image:latest
    build:
      context: .
    container_name: student-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://api-database:5432/student-api-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres-database
    links:
      - postgres-database

volumes:
  postgres-data: