name: Deployment Workflow
on: push
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build artifact with Maven
        run: mvn clean install -DskipTests
      - name: running docker compose file
        run: docker-compose up -d
      - name: list all images
        run: docker images
      - name: list running containers
        run: docker ps
      - name: list all containers
        run: docker ps -a
